

export  const listLink = {
    index:"/",
    home:"/*",
    affichage:"/publicites",
    carte:"/publicites-sur-carte",
    media:"/medias",
    panier:"/panier",
    radio_:"/radios/*",
    radio:"/radios",
    produit:"produits",
    devis:"devis",
    referencer:"/referencer-un-media",
    telecharger_devis:"telecharger-le-devis",
    tele_:"/televisions/*",
    tele:"/televisions",
    presse_:"/presse-ecrite/*",
    presse:"/presse-ecrite",
    journaux_:"/journaux-en-ligne/*",
    journaux:"/journaux-en-ligne",
    dashboard_:"/tableau-de-bord/*",
    dashboard:"/tableau-de-bord/",
    dashboard_home:"tableau-de-bord/",
    dashboard_demande:"demandes",
    dashboard_campagne:"campagne",
    dashboard_devis:"devis",
    dashboard_paiement:"paiement",
    dashboard_support_:"supports-publicitaires/*",
    dashboard_support:"supports-publicitaires",
    dashboard_docs:"mes-documents",
    dashboard_compte:"compte",
    dashboard_admin:"administration",
    dashboard_liste_media:"liste-medias"
}
